plugins {
    id 'com.android.application'
}

android {
    namespace 'technology.greatindia.biznest'
    compileSdk 35

    defaultConfig {
        applicationId "technology.greatindia.biznest"
        minSdk 23
        targetSdk 35

        versionCode 1
        versionName "1.0.0"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }

        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
